<a href="https://colab.research.google.com/github/AkashYadav-02/python/blob/main/numpy_part_4_eng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##Sort, Search & Counting Functions.

In [ ]:
import numpy as np

In [ ]:
arr = np.array([4,2,8,5,3,9,12,56])

In [ ]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [ ]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [ ]:
np.searchsorted(arr,6)

5

In [ ]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [ ]:
np.count_nonzero(arr1)

6

In [ ]:
np.where(arr1 > 0 )

(array([1, 2, 3, 4, 5, 9]),)

In [ ]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [ ]:
#Numpy - Byte Swapping.

In [ ]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
arr.byteswap(True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [ ]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [ ]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [ ]:
#Numpy - Copies &Views.

In [ ]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
a = np.copy(arr1)

In [ ]:
b = arr1.view()

In [ ]:
b = arr1

In [ ]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
b[0] = 234

In [ ]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
#Numpy - Matrix Library.

In [ ]:
import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
#Numpy - Linear Algebra

In [ ]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [ ]:
arr2 = np.random.randint([[5,3] , [2,5]])


In [ ]:
arr1

array([[0, 1],
       [1, 4]])

In [ ]:
arr2

array([[2, 2],
       [1, 2]])

In [ ]:
np.dot(arr1,arr2)

array([[ 1,  2],
       [ 6, 10]])

In [ ]:
arr1@arr2

array([[ 1,  2],
       [ 6, 10]])